version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "888:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "../app:/var/www/html"
    links:
      - php
  php:
    build: php
    volumes:
      - "../app:/var/www/html"
